<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	0x7fb541ca9171: ccl_err + 0x8171 (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0xb1)
	0x7fb541cac015: ccl_err + 0xb015 (_Z14err_terminatorv + 0x4b)
	0x7fb539fa69ec: stdc++.so.6 + 0xaa9ec
	0x7fb539fa6a47: stdc++.so.6 + 0xaaa47
	0x7fb539fa6cfd: stdc++.so.6 + 0xaacfd (__cxa_rethrow + 0x4d)
	0x7fb5656fbb64: QtCore.so.4 + 0x1a5b64 (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x2f4)
	0x7fb5657007c4: QtCore.so.4 + 0x1aa7c4 (_ZN16QCoreApplication4execEv + 0xb4)
	   0x401ea8: quartus + 0x1ea8 (_Z8qgq_mainiPPKc + 0x68)
	0x7fb544517720: ccl_msg + 0x40720 (_Z15msg_main_threadPv + 0x10)
	0x7fb54186902c: ccl_thr + 0x602c (thr_final_wrapper + 0xc)
	0x7fb5445177df: ccl_msg + 0x407df (_Z18msg_thread_wrapperPFPvS_ES_ + 0x62)
	0x7fb541edc559: ccl_mem + 0xa559 (_Z18mem_thread_wrapperPFPvS_ES_ + 0x99)
	0x7fb541ca9f92: ccl_err + 0x8f92 (_Z18err_thread_wrapperPFPvS_ES_ + 0x27)
	0x7fb5418693f2: ccl_thr + 0x63f2 (thr_thread_wrapper + 0x15)
	0x7fb5445197e2: ccl_msg + 0x427e2 (_Z12msg_exe_mainiPPKcPFiiS1_E + 0xa3)
	   0x401f7a: quartus + 0x1f7a (main + 0x26)
	0x7fb5397bd1e3: c.so.6 + 0x271e3 (__libc_start_main + 0xf3)
	   0x401d59: quartus + 0x1d59
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Fri May 29 00:12:25 2020
</date>
<version>Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition</version>
</internal_error>